// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type MachineModelsLaserType string

const (
	MachineModelsLaserTypeCO2   MachineModelsLaserType = "CO2"
	MachineModelsLaserTypeDiode MachineModelsLaserType = "Diode"
	MachineModelsLaserTypeFiber MachineModelsLaserType = "Fiber"
)

func (e *MachineModelsLaserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MachineModelsLaserType(s)
	case string:
		*e = MachineModelsLaserType(s)
	default:
		return fmt.Errorf("unsupported scan type for MachineModelsLaserType: %T", src)
	}
	return nil
}

type NullMachineModelsLaserType struct {
	MachineModelsLaserType MachineModelsLaserType
	Valid                  bool // Valid is true if MachineModelsLaserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMachineModelsLaserType) Scan(value interface{}) error {
	if value == nil {
		ns.MachineModelsLaserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MachineModelsLaserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMachineModelsLaserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MachineModelsLaserType), nil
}

type MachineBrand struct {
	ID   int32
	Name string
	Slug string
}

type MachineModel struct {
	ID        int32
	BrandID   int32
	Name      string
	LaserType MachineModelsLaserType
	Wattage   int32
	Slug      string
}

type Material struct {
	ID         int32
	CategoryID int32
	Name       string
	Slug       string
}

type MaterialAlias struct {
	ID         int32
	MaterialID int32
	Alias      string
}

type MaterialCategory struct {
	ID   int32
	Name string
}

type Operation struct {
	ID   int32
	Name string
}

type Setting struct {
	ID             int32
	UserID         int32
	MachineModelID int32
	MaterialID     int32
	OperationID    int32
	Power          int32
	Speed          int32
	Passes         int32
	Frequency      sql.NullInt32
	Dpi            sql.NullInt32
	Notes          sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	DisplayName  sql.NullString
	CreatedAt    sql.NullTime
}

type Vote struct {
	ID        int32
	UserID    int32
	SettingID int32
	Value     int8
	CreatedAt sql.NullTime
}
