// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type SettingsLaserType string

const (
	SettingsLaserTypeCO2      SettingsLaserType = "CO2"
	SettingsLaserTypeFiber    SettingsLaserType = "Fiber"
	SettingsLaserTypeDiode    SettingsLaserType = "Diode"
	SettingsLaserTypeUV       SettingsLaserType = "UV"
	SettingsLaserTypeInfrared SettingsLaserType = "Infrared"
)

func (e *SettingsLaserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettingsLaserType(s)
	case string:
		*e = SettingsLaserType(s)
	default:
		return fmt.Errorf("unsupported scan type for SettingsLaserType: %T", src)
	}
	return nil
}

type NullSettingsLaserType struct {
	SettingsLaserType SettingsLaserType
	Valid             bool // Valid is true if SettingsLaserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettingsLaserType) Scan(value interface{}) error {
	if value == nil {
		ns.SettingsLaserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettingsLaserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettingsLaserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettingsLaserType), nil
}

type SettingsOperationType string

const (
	SettingsOperationTypeCut     SettingsOperationType = "Cut"
	SettingsOperationTypeScan    SettingsOperationType = "Scan"
	SettingsOperationTypeScanCut SettingsOperationType = "ScanCut"
)

func (e *SettingsOperationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettingsOperationType(s)
	case string:
		*e = SettingsOperationType(s)
	default:
		return fmt.Errorf("unsupported scan type for SettingsOperationType: %T", src)
	}
	return nil
}

type NullSettingsOperationType struct {
	SettingsOperationType SettingsOperationType
	Valid                 bool // Valid is true if SettingsOperationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettingsOperationType) Scan(value interface{}) error {
	if value == nil {
		ns.SettingsOperationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettingsOperationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettingsOperationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettingsOperationType), nil
}

type Material struct {
	ID         int32
	CategoryID int32
	Name       string
	Slug       string
}

type MaterialAlias struct {
	ID         int32
	MaterialID int32
	Alias      string
}

type MaterialCategory struct {
	ID   int32
	Name string
}

type Setting struct {
	ID               int32
	UserID           int32
	MaterialID       int32
	LaserType        SettingsLaserType
	Wattage          int32
	OperationType    SettingsOperationType
	MaxPower         string
	MinPower         string
	MaxPower2        sql.NullString
	MinPower2        sql.NullString
	Speed            string
	NumPasses        int32
	ZOffset          sql.NullString
	ZPerPass         sql.NullString
	ScanInterval     sql.NullString
	Angle            sql.NullString
	AnglePerPass     sql.NullString
	CrossHatch       bool
	Bidir            bool
	ScanOpt          sql.NullString
	FloodFill        bool
	AutoRotate       bool
	Overscan         sql.NullString
	OverscanPercent  sql.NullString
	Frequency        sql.NullString
	WobbleEnable     sql.NullBool
	UseDotCorrection sql.NullBool
	Kerf             sql.NullString
	RunBlower        sql.NullBool
	LayerName        sql.NullString
	LayerSubname     sql.NullString
	Priority         sql.NullInt32
	TabCount         sql.NullInt32
	TabCountMax      sql.NullInt32
	Notes            sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	DisplayName  sql.NullString
	CreatedAt    sql.NullTime
}

type Vote struct {
	ID        int32
	UserID    int32
	SettingID int32
	Value     int8
	CreatedAt sql.NullTime
}
