// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createMaterial = `-- name: CreateMaterial :execresult
INSERT INTO materials (category_id, name, slug)
VALUES (?, ?, ?)
`

type CreateMaterialParams struct {
	CategoryID int32
	Name       string
	Slug       string
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMaterial, arg.CategoryID, arg.Name, arg.Slug)
}

const createSetting = `-- name: CreateSetting :execresult
INSERT INTO settings (
    user_id, material_id, laser_type, wattage, operation_type,
    max_power, min_power, max_power2, min_power2, speed,
    num_passes, z_offset, z_per_pass,
    scan_interval, angle, angle_per_pass,
    cross_hatch, bidir, scan_opt,
    flood_fill, auto_rotate, overscan, overscan_percent,
    frequency, wobble_enable, use_dot_correction,
    perforation_mode, dot_width,
    image_mode, negative_image,
    kerf, run_blower,
    layer_name, layer_subname,
    priority, tab_count, tab_count_max,
    notes
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?, ?,
    ?
)
`

type CreateSettingParams struct {
	UserID           int32
	MaterialID       int32
	LaserType        SettingsLaserType
	Wattage          int32
	OperationType    SettingsOperationType
	MaxPower         string
	MinPower         string
	MaxPower2        sql.NullString
	MinPower2        sql.NullString
	Speed            string
	NumPasses        int32
	ZOffset          sql.NullString
	ZPerPass         sql.NullString
	ScanInterval     sql.NullString
	Angle            sql.NullString
	AnglePerPass     sql.NullString
	CrossHatch       bool
	Bidir            bool
	ScanOpt          sql.NullString
	FloodFill        bool
	AutoRotate       bool
	Overscan         sql.NullString
	OverscanPercent  sql.NullString
	Frequency        sql.NullString
	WobbleEnable     sql.NullBool
	UseDotCorrection sql.NullBool
	PerforationMode  bool
	DotWidth         sql.NullString
	ImageMode        sql.NullString
	NegativeImage    bool
	Kerf             sql.NullString
	RunBlower        sql.NullBool
	LayerName        sql.NullString
	LayerSubname     sql.NullString
	Priority         sql.NullInt32
	TabCount         sql.NullInt32
	TabCountMax      sql.NullInt32
	Notes            sql.NullString
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSetting,
		arg.UserID,
		arg.MaterialID,
		arg.LaserType,
		arg.Wattage,
		arg.OperationType,
		arg.MaxPower,
		arg.MinPower,
		arg.MaxPower2,
		arg.MinPower2,
		arg.Speed,
		arg.NumPasses,
		arg.ZOffset,
		arg.ZPerPass,
		arg.ScanInterval,
		arg.Angle,
		arg.AnglePerPass,
		arg.CrossHatch,
		arg.Bidir,
		arg.ScanOpt,
		arg.FloodFill,
		arg.AutoRotate,
		arg.Overscan,
		arg.OverscanPercent,
		arg.Frequency,
		arg.WobbleEnable,
		arg.UseDotCorrection,
		arg.PerforationMode,
		arg.DotWidth,
		arg.ImageMode,
		arg.NegativeImage,
		arg.Kerf,
		arg.RunBlower,
		arg.LayerName,
		arg.LayerSubname,
		arg.Priority,
		arg.TabCount,
		arg.TabCountMax,
		arg.Notes,
	)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (first_name, last_name, email, password_hash, display_name)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	DisplayName  sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings
WHERE id = ? AND user_id = ?
`

type DeleteSettingParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteSetting(ctx context.Context, arg DeleteSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, arg.ID, arg.UserID)
	return err
}

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM votes
WHERE user_id = ? AND setting_id = ?
`

type DeleteVoteParams struct {
	UserID    int32
	SettingID int32
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteVote, arg.UserID, arg.SettingID)
	return err
}

const getAdminStats = `-- name: GetAdminStats :one

SELECT
    (SELECT COUNT(*) FROM users) as total_users,
    (SELECT COUNT(*) FROM users WHERE email_verified = TRUE) as verified_users,
    (SELECT COUNT(*) FROM users WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)) as users_this_week,
    (SELECT COUNT(*) FROM settings) as total_settings,
    (SELECT COUNT(*) FROM settings WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)) as settings_this_week,
    (SELECT COUNT(*) FROM votes) as total_votes,
    (SELECT COUNT(*) FROM votes WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)) as votes_this_week
`

type GetAdminStatsRow struct {
	TotalUsers       int64
	VerifiedUsers    int64
	UsersThisWeek    int64
	TotalSettings    int64
	SettingsThisWeek int64
	TotalVotes       int64
	VotesThisWeek    int64
}

// =====================
// ADMIN QUERIES
// =====================
func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.VerifiedUsers,
		&i.UsersThisWeek,
		&i.TotalSettings,
		&i.SettingsThisWeek,
		&i.TotalVotes,
		&i.VotesThisWeek,
	)
	return i, err
}

const getAliasesByMaterial = `-- name: GetAliasesByMaterial :many
SELECT id, material_id, alias
FROM material_aliases
WHERE material_id = ?
ORDER BY alias
`

func (q *Queries) GetAliasesByMaterial(ctx context.Context, materialID int32) ([]MaterialAlias, error) {
	rows, err := q.db.QueryContext(ctx, getAliasesByMaterial, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaterialAlias
	for rows.Next() {
		var i MaterialAlias
		if err := rows.Scan(&i.ID, &i.MaterialID, &i.Alias); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategories = `-- name: GetAllCategories :many

SELECT id, name
FROM material_categories
ORDER BY name
`

// =====================
// MATERIAL CATEGORIES
// =====================
func (q *Queries) GetAllCategories(ctx context.Context) ([]MaterialCategory, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaterialCategory
	for rows.Next() {
		var i MaterialCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMaterials = `-- name: GetAllMaterials :many

SELECT m.id, m.category_id, m.name, m.slug,
       c.name as category_name
FROM materials m
JOIN material_categories c ON m.category_id = c.id
ORDER BY c.name, m.name
`

type GetAllMaterialsRow struct {
	ID           int32
	CategoryID   int32
	Name         string
	Slug         string
	CategoryName string
}

// =====================
// MATERIALS
// =====================
func (q *Queries) GetAllMaterials(ctx context.Context) ([]GetAllMaterialsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMaterialsRow
	for rows.Next() {
		var i GetAllMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSettingsAdmin = `-- name: GetAllSettingsAdmin :many
SELECT s.id, s.user_id, s.material_id, s.laser_type, s.wattage, s.operation_type,
       s.max_power, s.min_power, s.speed, s.created_at,
       u.email as user_email, u.display_name as user_display_name,
       m.name as material_name,
       CAST(COALESCE(SUM(v.value), 0) AS SIGNED) as vote_score
FROM settings s
JOIN users u ON s.user_id = u.id
JOIN materials m ON s.material_id = m.id
LEFT JOIN votes v ON v.setting_id = s.id
WHERE (? IS NULL OR s.material_id = ?)
  AND (? IS NULL OR s.laser_type = ?)
GROUP BY s.id
ORDER BY s.created_at DESC
LIMIT ? OFFSET ?
`

type GetAllSettingsAdminParams struct {
	MaterialID sql.NullInt32
	LaserType  NullSettingsLaserType
	Limit      int32
	Offset     int32
}

type GetAllSettingsAdminRow struct {
	ID              int32
	UserID          int32
	MaterialID      int32
	LaserType       SettingsLaserType
	Wattage         int32
	OperationType   SettingsOperationType
	MaxPower        string
	MinPower        string
	Speed           string
	CreatedAt       sql.NullTime
	UserEmail       string
	UserDisplayName sql.NullString
	MaterialName    string
	VoteScore       int64
}

func (q *Queries) GetAllSettingsAdmin(ctx context.Context, arg GetAllSettingsAdminParams) ([]GetAllSettingsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSettingsAdmin,
		arg.MaterialID,
		arg.MaterialID,
		arg.LaserType,
		arg.LaserType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSettingsAdminRow
	for rows.Next() {
		var i GetAllSettingsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MaterialID,
			&i.LaserType,
			&i.Wattage,
			&i.OperationType,
			&i.MaxPower,
			&i.MinPower,
			&i.Speed,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserDisplayName,
			&i.MaterialName,
			&i.VoteScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersAdmin = `-- name: GetAllUsersAdmin :many
SELECT u.id, u.first_name, u.last_name, u.email, u.display_name, u.email_verified, u.is_admin, u.created_at,
       COUNT(s.id) as setting_count
FROM users u
LEFT JOIN settings s ON s.user_id = u.id
WHERE (? IS NULL OR u.email LIKE CONCAT('%', ?, '%'))
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT ? OFFSET ?
`

type GetAllUsersAdminParams struct {
	Search interface{}
	Limit  int32
	Offset int32
}

type GetAllUsersAdminRow struct {
	ID            int32
	FirstName     string
	LastName      string
	Email         string
	DisplayName   sql.NullString
	EmailVerified bool
	IsAdmin       bool
	CreatedAt     sql.NullTime
	SettingCount  int64
}

func (q *Queries) GetAllUsersAdmin(ctx context.Context, arg GetAllUsersAdminParams) ([]GetAllUsersAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersAdmin,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersAdminRow
	for rows.Next() {
		var i GetAllUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.DisplayName,
			&i.EmailVerified,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.SettingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialByID = `-- name: GetMaterialByID :one
SELECT m.id, m.category_id, m.name, m.slug,
       c.name as category_name
FROM materials m
JOIN material_categories c ON m.category_id = c.id
WHERE m.id = ?
`

type GetMaterialByIDRow struct {
	ID           int32
	CategoryID   int32
	Name         string
	Slug         string
	CategoryName string
}

func (q *Queries) GetMaterialByID(ctx context.Context, id int32) (GetMaterialByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMaterialByID, id)
	var i GetMaterialByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.CategoryName,
	)
	return i, err
}

const getMaterialByName = `-- name: GetMaterialByName :one
SELECT id, category_id, name, slug
FROM materials
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetMaterialByName(ctx context.Context, name string) (Material, error) {
	row := q.db.QueryRowContext(ctx, getMaterialByName, name)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
	)
	return i, err
}

const getMaterialsByCategory = `-- name: GetMaterialsByCategory :many
SELECT id, category_id, name, slug
FROM materials
WHERE category_id = ?
ORDER BY name
`

func (q *Queries) GetMaterialsByCategory(ctx context.Context, categoryID int32) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, getMaterialsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingByID = `-- name: GetSettingByID :one

SELECT s.id, s.user_id, s.material_id,
       s.laser_type, s.wattage, s.operation_type,
       s.max_power, s.min_power, s.max_power2, s.min_power2, s.speed,
       s.num_passes, s.z_offset, s.z_per_pass,
       s.scan_interval, s.angle, s.angle_per_pass,
       s.cross_hatch, s.bidir, s.scan_opt,
       s.flood_fill, s.auto_rotate, s.overscan, s.overscan_percent,
       s.frequency, s.wobble_enable, s.use_dot_correction,
       s.kerf, s.run_blower,
       s.layer_name, s.layer_subname,
       s.priority, s.tab_count, s.tab_count_max,
       s.notes, s.created_at, s.updated_at,
       u.first_name, u.last_name, u.display_name,
       mat.name as material_name, mc.name as category_name,
       CAST(COALESCE(SUM(v.value), 0) AS SIGNED) as vote_score,
       COUNT(v.id) as vote_count
FROM settings s
JOIN users u ON s.user_id = u.id
JOIN materials mat ON s.material_id = mat.id
JOIN material_categories mc ON mat.category_id = mc.id
LEFT JOIN votes v ON v.setting_id = s.id
WHERE s.id = ?
GROUP BY s.id
`

type GetSettingByIDRow struct {
	ID               int32
	UserID           int32
	MaterialID       int32
	LaserType        SettingsLaserType
	Wattage          int32
	OperationType    SettingsOperationType
	MaxPower         string
	MinPower         string
	MaxPower2        sql.NullString
	MinPower2        sql.NullString
	Speed            string
	NumPasses        int32
	ZOffset          sql.NullString
	ZPerPass         sql.NullString
	ScanInterval     sql.NullString
	Angle            sql.NullString
	AnglePerPass     sql.NullString
	CrossHatch       bool
	Bidir            bool
	ScanOpt          sql.NullString
	FloodFill        bool
	AutoRotate       bool
	Overscan         sql.NullString
	OverscanPercent  sql.NullString
	Frequency        sql.NullString
	WobbleEnable     sql.NullBool
	UseDotCorrection sql.NullBool
	Kerf             sql.NullString
	RunBlower        sql.NullBool
	LayerName        sql.NullString
	LayerSubname     sql.NullString
	Priority         sql.NullInt32
	TabCount         sql.NullInt32
	TabCountMax      sql.NullInt32
	Notes            sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	FirstName        string
	LastName         string
	DisplayName      sql.NullString
	MaterialName     string
	CategoryName     string
	VoteScore        int64
	VoteCount        int64
}

// =====================
// SETTINGS
// =====================
func (q *Queries) GetSettingByID(ctx context.Context, id int32) (GetSettingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSettingByID, id)
	var i GetSettingByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaterialID,
		&i.LaserType,
		&i.Wattage,
		&i.OperationType,
		&i.MaxPower,
		&i.MinPower,
		&i.MaxPower2,
		&i.MinPower2,
		&i.Speed,
		&i.NumPasses,
		&i.ZOffset,
		&i.ZPerPass,
		&i.ScanInterval,
		&i.Angle,
		&i.AnglePerPass,
		&i.CrossHatch,
		&i.Bidir,
		&i.ScanOpt,
		&i.FloodFill,
		&i.AutoRotate,
		&i.Overscan,
		&i.OverscanPercent,
		&i.Frequency,
		&i.WobbleEnable,
		&i.UseDotCorrection,
		&i.Kerf,
		&i.RunBlower,
		&i.LayerName,
		&i.LayerSubname,
		&i.Priority,
		&i.TabCount,
		&i.TabCountMax,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.MaterialName,
		&i.CategoryName,
		&i.VoteScore,
		&i.VoteCount,
	)
	return i, err
}

const getSettingsByLaserType = `-- name: GetSettingsByLaserType :many
SELECT laser_type, COUNT(*) as count
FROM settings
GROUP BY laser_type
ORDER BY count DESC
`

type GetSettingsByLaserTypeRow struct {
	LaserType SettingsLaserType
	Count     int64
}

func (q *Queries) GetSettingsByLaserType(ctx context.Context) ([]GetSettingsByLaserTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getSettingsByLaserType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSettingsByLaserTypeRow
	for rows.Next() {
		var i GetSettingsByLaserTypeRow
		if err := rows.Scan(&i.LaserType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingsCountAdmin = `-- name: GetSettingsCountAdmin :one
SELECT COUNT(*) as total
FROM settings s
WHERE (? IS NULL OR s.material_id = ?)
  AND (? IS NULL OR s.laser_type = ?)
`

type GetSettingsCountAdminParams struct {
	MaterialID sql.NullInt32
	LaserType  NullSettingsLaserType
}

func (q *Queries) GetSettingsCountAdmin(ctx context.Context, arg GetSettingsCountAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSettingsCountAdmin,
		arg.MaterialID,
		arg.MaterialID,
		arg.LaserType,
		arg.LaserType,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTopMaterialsBySettings = `-- name: GetTopMaterialsBySettings :many
SELECT m.name as material_name, COUNT(s.id) as setting_count
FROM materials m
JOIN settings s ON s.material_id = m.id
GROUP BY m.id, m.name
ORDER BY setting_count DESC
LIMIT 5
`

type GetTopMaterialsBySettingsRow struct {
	MaterialName string
	SettingCount int64
}

func (q *Queries) GetTopMaterialsBySettings(ctx context.Context) ([]GetTopMaterialsBySettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopMaterialsBySettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMaterialsBySettingsRow
	for rows.Next() {
		var i GetTopMaterialsBySettingsRow
		if err := rows.Scan(&i.MaterialName, &i.SettingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSettings = `-- name: GetTopSettings :many
SELECT s.id, s.user_id, s.material_id,
       s.laser_type, s.wattage, s.operation_type,
       s.max_power, s.min_power, s.speed,
       s.num_passes, s.scan_interval, s.frequency,
       s.cross_hatch, s.bidir, s.angle, s.angle_per_pass,
       s.image_mode, s.negative_image,
       s.use_dot_correction, s.dot_width,
       s.notes, s.created_at,
       u.first_name, u.last_name, u.display_name,
       mat.name as material_name, mc.name as category_name,
       CAST(COALESCE(SUM(v.value), 0) AS SIGNED) as vote_score,
       COUNT(v.id) as vote_count
FROM settings s
JOIN users u ON s.user_id = u.id
JOIN materials mat ON s.material_id = mat.id
JOIN material_categories mc ON mat.category_id = mc.id
LEFT JOIN votes v ON v.setting_id = s.id
GROUP BY s.id
ORDER BY vote_score DESC
LIMIT 20
`

type GetTopSettingsRow struct {
	ID               int32
	UserID           int32
	MaterialID       int32
	LaserType        SettingsLaserType
	Wattage          int32
	OperationType    SettingsOperationType
	MaxPower         string
	MinPower         string
	Speed            string
	NumPasses        int32
	ScanInterval     sql.NullString
	Frequency        sql.NullString
	CrossHatch       bool
	Bidir            bool
	Angle            sql.NullString
	AnglePerPass     sql.NullString
	ImageMode        sql.NullString
	NegativeImage    bool
	UseDotCorrection sql.NullBool
	DotWidth         sql.NullString
	Notes            sql.NullString
	CreatedAt        sql.NullTime
	FirstName        string
	LastName         string
	DisplayName      sql.NullString
	MaterialName     string
	CategoryName     string
	VoteScore        int64
	VoteCount        int64
}

func (q *Queries) GetTopSettings(ctx context.Context) ([]GetTopSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSettingsRow
	for rows.Next() {
		var i GetTopSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MaterialID,
			&i.LaserType,
			&i.Wattage,
			&i.OperationType,
			&i.MaxPower,
			&i.MinPower,
			&i.Speed,
			&i.NumPasses,
			&i.ScanInterval,
			&i.Frequency,
			&i.CrossHatch,
			&i.Bidir,
			&i.Angle,
			&i.AnglePerPass,
			&i.ImageMode,
			&i.NegativeImage,
			&i.UseDotCorrection,
			&i.DotWidth,
			&i.Notes,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.MaterialName,
			&i.CategoryName,
			&i.VoteScore,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password_hash, display_name, email_verified, is_admin, created_at
FROM users
WHERE email = ?
`

type GetUserByEmailRow struct {
	ID            int32
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	DisplayName   sql.NullString
	EmailVerified bool
	IsAdmin       bool
	CreatedAt     sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, first_name, last_name, email, password_hash, display_name, email_verified, is_admin, created_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID            int32
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	DisplayName   sql.NullString
	EmailVerified bool
	IsAdmin       bool
	CreatedAt     sql.NullTime
}

// =====================
// USERS
// =====================
func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIDAdmin = `-- name: GetUserByIDAdmin :one
SELECT u.id, u.first_name, u.last_name, u.email, u.display_name, u.email_verified, u.is_admin, u.created_at,
       COUNT(s.id) as setting_count
FROM users u
LEFT JOIN settings s ON s.user_id = u.id
WHERE u.id = ?
GROUP BY u.id
`

type GetUserByIDAdminRow struct {
	ID            int32
	FirstName     string
	LastName      string
	Email         string
	DisplayName   sql.NullString
	EmailVerified bool
	IsAdmin       bool
	CreatedAt     sql.NullTime
	SettingCount  int64
}

func (q *Queries) GetUserByIDAdmin(ctx context.Context, id int32) (GetUserByIDAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDAdmin, id)
	var i GetUserByIDAdminRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DisplayName,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.SettingCount,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, first_name, last_name, email, email_verified, verification_expires
FROM users
WHERE verification_token = ?
`

type GetUserByVerificationTokenRow struct {
	ID                  int32
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       bool
	VerificationExpires sql.NullTime
}

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken sql.NullString) (GetUserByVerificationTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByVerificationToken, verificationToken)
	var i GetUserByVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.VerificationExpires,
	)
	return i, err
}

const getUserCountAdmin = `-- name: GetUserCountAdmin :one
SELECT COUNT(*) as total
FROM users
WHERE (? IS NULL OR email LIKE CONCAT('%', ?, '%'))
`

type GetUserCountAdminParams struct {
	Search interface{}
}

func (q *Queries) GetUserCountAdmin(ctx context.Context, arg GetUserCountAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCountAdmin, arg.Search, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUserSettings = `-- name: GetUserSettings :many
SELECT s.id, s.user_id, s.material_id,
       s.laser_type, s.wattage, s.operation_type,
       s.max_power, s.min_power, s.speed,
       s.num_passes, s.scan_interval, s.frequency,
       s.cross_hatch, s.bidir, s.angle, s.angle_per_pass,
       s.flood_fill, s.auto_rotate, s.wobble_enable,
       s.perforation_mode, s.use_dot_correction, s.dot_width,
       s.image_mode, s.negative_image,
       s.notes, s.created_at, s.updated_at,
       mat.name as material_name, mc.name as category_name,
       CAST(COALESCE(SUM(v.value), 0) AS SIGNED) as vote_score,
       COUNT(v.id) as vote_count
FROM settings s
JOIN materials mat ON s.material_id = mat.id
JOIN material_categories mc ON mat.category_id = mc.id
LEFT JOIN votes v ON v.setting_id = s.id
WHERE s.user_id = ?
GROUP BY s.id
ORDER BY s.created_at DESC
`

type GetUserSettingsRow struct {
	ID               int32
	UserID           int32
	MaterialID       int32
	LaserType        SettingsLaserType
	Wattage          int32
	OperationType    SettingsOperationType
	MaxPower         string
	MinPower         string
	Speed            string
	NumPasses        int32
	ScanInterval     sql.NullString
	Frequency        sql.NullString
	CrossHatch       bool
	Bidir            bool
	Angle            sql.NullString
	AnglePerPass     sql.NullString
	FloodFill        bool
	AutoRotate       bool
	WobbleEnable     sql.NullBool
	PerforationMode  bool
	UseDotCorrection sql.NullBool
	DotWidth         sql.NullString
	ImageMode        sql.NullString
	NegativeImage    bool
	Notes            sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	MaterialName     string
	CategoryName     string
	VoteScore        int64
	VoteCount        int64
}

func (q *Queries) GetUserSettings(ctx context.Context, userID int32) ([]GetUserSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSettingsRow
	for rows.Next() {
		var i GetUserSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MaterialID,
			&i.LaserType,
			&i.Wattage,
			&i.OperationType,
			&i.MaxPower,
			&i.MinPower,
			&i.Speed,
			&i.NumPasses,
			&i.ScanInterval,
			&i.Frequency,
			&i.CrossHatch,
			&i.Bidir,
			&i.Angle,
			&i.AnglePerPass,
			&i.FloodFill,
			&i.AutoRotate,
			&i.WobbleEnable,
			&i.PerforationMode,
			&i.UseDotCorrection,
			&i.DotWidth,
			&i.ImageMode,
			&i.NegativeImage,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaterialName,
			&i.CategoryName,
			&i.VoteScore,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVoteForSetting = `-- name: GetUserVoteForSetting :one

SELECT id, user_id, setting_id, value, created_at
FROM votes
WHERE user_id = ? AND setting_id = ?
`

type GetUserVoteForSettingParams struct {
	UserID    int32
	SettingID int32
}

// =====================
// VOTES
// =====================
func (q *Queries) GetUserVoteForSetting(ctx context.Context, arg GetUserVoteForSettingParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, getUserVoteForSetting, arg.UserID, arg.SettingID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SettingID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteScore = `-- name: GetVoteScore :one
SELECT COALESCE(SUM(value), 0) as score, COUNT(id) as total
FROM votes
WHERE setting_id = ?
`

type GetVoteScoreRow struct {
	Score interface{}
	Total int64
}

func (q *Queries) GetVoteScore(ctx context.Context, settingID int32) (GetVoteScoreRow, error) {
	row := q.db.QueryRowContext(ctx, getVoteScore, settingID)
	var i GetVoteScoreRow
	err := row.Scan(&i.Score, &i.Total)
	return i, err
}

const searchMaterials = `-- name: SearchMaterials :many
SELECT m.id, m.category_id, m.name, m.slug,
       c.name as category_name
FROM materials m
JOIN material_categories c ON m.category_id = c.id
WHERE m.name LIKE CONCAT('%', ?, '%')
   OR m.slug LIKE CONCAT('%', ?, '%')
ORDER BY m.name
LIMIT 20
`

type SearchMaterialsParams struct {
	CONCAT   interface{}
	CONCAT_2 interface{}
}

type SearchMaterialsRow struct {
	ID           int32
	CategoryID   int32
	Name         string
	Slug         string
	CategoryName string
}

func (q *Queries) SearchMaterials(ctx context.Context, arg SearchMaterialsParams) ([]SearchMaterialsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMaterials, arg.CONCAT, arg.CONCAT_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMaterialsRow
	for rows.Next() {
		var i SearchMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMaterialsWithAliases = `-- name: SearchMaterialsWithAliases :many
SELECT DISTINCT m.id, m.category_id, m.name, m.slug,
       c.name as category_name
FROM materials m
JOIN material_categories c ON m.category_id = c.id
LEFT JOIN material_aliases ma ON ma.material_id = m.id
WHERE m.name LIKE CONCAT('%', ?, '%')
   OR m.slug LIKE CONCAT('%', ?, '%')
   OR ma.alias LIKE CONCAT('%', ?, '%')
ORDER BY m.name
LIMIT 20
`

type SearchMaterialsWithAliasesParams struct {
	CONCAT   interface{}
	CONCAT_2 interface{}
	CONCAT_3 interface{}
}

type SearchMaterialsWithAliasesRow struct {
	ID           int32
	CategoryID   int32
	Name         string
	Slug         string
	CategoryName string
}

func (q *Queries) SearchMaterialsWithAliases(ctx context.Context, arg SearchMaterialsWithAliasesParams) ([]SearchMaterialsWithAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMaterialsWithAliases, arg.CONCAT, arg.CONCAT_2, arg.CONCAT_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMaterialsWithAliasesRow
	for rows.Next() {
		var i SearchMaterialsWithAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSettings = `-- name: SearchSettings :many
SELECT s.id, s.user_id, s.material_id,
       s.laser_type, s.wattage, s.operation_type,
       s.max_power, s.min_power, s.speed,
       s.num_passes, s.scan_interval, s.frequency,
       s.cross_hatch, s.bidir, s.angle, s.angle_per_pass,
       s.image_mode, s.negative_image,
       s.use_dot_correction, s.dot_width,
       s.notes, s.created_at,
       u.first_name, u.last_name, u.display_name,
       mat.name as material_name, mc.name as category_name,
       CAST(COALESCE(SUM(v.value), 0) AS SIGNED) as vote_score,
       COUNT(v.id) as vote_count
FROM settings s
JOIN users u ON s.user_id = u.id
JOIN materials mat ON s.material_id = mat.id
JOIN material_categories mc ON mat.category_id = mc.id
LEFT JOIN votes v ON v.setting_id = s.id
WHERE (? IS NULL OR s.material_id = ?)
  AND (? IS NULL OR s.laser_type = ?)
  AND (? IS NULL OR s.wattage = ?)
  AND (? IS NULL OR s.operation_type = ?)
  AND (? IS NULL OR s.user_id = ?)
  AND (? IS NULL OR mat.name LIKE CONCAT('%', ?, '%'))
GROUP BY s.id
ORDER BY vote_score DESC, s.created_at DESC
LIMIT 50
`

type SearchSettingsParams struct {
	MaterialID    sql.NullInt32
	LaserType     NullSettingsLaserType
	Wattage       sql.NullInt32
	OperationType NullSettingsOperationType
	UserID        sql.NullInt32
	Keyword       interface{}
}

type SearchSettingsRow struct {
	ID               int32
	UserID           int32
	MaterialID       int32
	LaserType        SettingsLaserType
	Wattage          int32
	OperationType    SettingsOperationType
	MaxPower         string
	MinPower         string
	Speed            string
	NumPasses        int32
	ScanInterval     sql.NullString
	Frequency        sql.NullString
	CrossHatch       bool
	Bidir            bool
	Angle            sql.NullString
	AnglePerPass     sql.NullString
	ImageMode        sql.NullString
	NegativeImage    bool
	UseDotCorrection sql.NullBool
	DotWidth         sql.NullString
	Notes            sql.NullString
	CreatedAt        sql.NullTime
	FirstName        string
	LastName         string
	DisplayName      sql.NullString
	MaterialName     string
	CategoryName     string
	VoteScore        int64
	VoteCount        int64
}

func (q *Queries) SearchSettings(ctx context.Context, arg SearchSettingsParams) ([]SearchSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSettings,
		arg.MaterialID,
		arg.MaterialID,
		arg.LaserType,
		arg.LaserType,
		arg.Wattage,
		arg.Wattage,
		arg.OperationType,
		arg.OperationType,
		arg.UserID,
		arg.UserID,
		arg.Keyword,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSettingsRow
	for rows.Next() {
		var i SearchSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MaterialID,
			&i.LaserType,
			&i.Wattage,
			&i.OperationType,
			&i.MaxPower,
			&i.MinPower,
			&i.Speed,
			&i.NumPasses,
			&i.ScanInterval,
			&i.Frequency,
			&i.CrossHatch,
			&i.Bidir,
			&i.Angle,
			&i.AnglePerPass,
			&i.ImageMode,
			&i.NegativeImage,
			&i.UseDotCorrection,
			&i.DotWidth,
			&i.Notes,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.MaterialName,
			&i.CategoryName,
			&i.VoteScore,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users SET verification_token = ?, verification_expires = ?
WHERE id = ?
`

type SetVerificationTokenParams struct {
	VerificationToken   sql.NullString
	VerificationExpires sql.NullTime
	ID                  int32
}

func (q *Queries) SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error {
	_, err := q.db.ExecContext(ctx, setVerificationToken, arg.VerificationToken, arg.VerificationExpires, arg.ID)
	return err
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE settings SET
    max_power = ?, min_power = ?, max_power2 = ?, min_power2 = ?, speed = ?,
    num_passes = ?, z_offset = ?, z_per_pass = ?,
    scan_interval = ?, angle = ?, angle_per_pass = ?,
    cross_hatch = ?, bidir = ?, scan_opt = ?,
    flood_fill = ?, auto_rotate = ?, overscan = ?, overscan_percent = ?,
    frequency = ?, wobble_enable = ?, use_dot_correction = ?,
    perforation_mode = ?, dot_width = ?,
    image_mode = ?, negative_image = ?,
    kerf = ?, run_blower = ?,
    layer_name = ?, layer_subname = ?,
    priority = ?, tab_count = ?, tab_count_max = ?,
    notes = ?
WHERE id = ? AND user_id = ?
`

type UpdateSettingParams struct {
	MaxPower         string
	MinPower         string
	MaxPower2        sql.NullString
	MinPower2        sql.NullString
	Speed            string
	NumPasses        int32
	ZOffset          sql.NullString
	ZPerPass         sql.NullString
	ScanInterval     sql.NullString
	Angle            sql.NullString
	AnglePerPass     sql.NullString
	CrossHatch       bool
	Bidir            bool
	ScanOpt          sql.NullString
	FloodFill        bool
	AutoRotate       bool
	Overscan         sql.NullString
	OverscanPercent  sql.NullString
	Frequency        sql.NullString
	WobbleEnable     sql.NullBool
	UseDotCorrection sql.NullBool
	PerforationMode  bool
	DotWidth         sql.NullString
	ImageMode        sql.NullString
	NegativeImage    bool
	Kerf             sql.NullString
	RunBlower        sql.NullBool
	LayerName        sql.NullString
	LayerSubname     sql.NullString
	Priority         sql.NullInt32
	TabCount         sql.NullInt32
	TabCountMax      sql.NullInt32
	Notes            sql.NullString
	ID               int32
	UserID           int32
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateSetting,
		arg.MaxPower,
		arg.MinPower,
		arg.MaxPower2,
		arg.MinPower2,
		arg.Speed,
		arg.NumPasses,
		arg.ZOffset,
		arg.ZPerPass,
		arg.ScanInterval,
		arg.Angle,
		arg.AnglePerPass,
		arg.CrossHatch,
		arg.Bidir,
		arg.ScanOpt,
		arg.FloodFill,
		arg.AutoRotate,
		arg.Overscan,
		arg.OverscanPercent,
		arg.Frequency,
		arg.WobbleEnable,
		arg.UseDotCorrection,
		arg.PerforationMode,
		arg.DotWidth,
		arg.ImageMode,
		arg.NegativeImage,
		arg.Kerf,
		arg.RunBlower,
		arg.LayerName,
		arg.LayerSubname,
		arg.Priority,
		arg.TabCount,
		arg.TabCountMax,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertVote = `-- name: UpsertVote :exec
INSERT INTO votes (user_id, setting_id, value)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE value = VALUES(value)
`

type UpsertVoteParams struct {
	UserID    int32
	SettingID int32
	Value     int8
}

func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertVote, arg.UserID, arg.SettingID, arg.Value)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified = TRUE, verification_token = NULL, verification_expires = NULL
WHERE id = ?
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, verifyUserEmail, id)
	return err
}
